

 export const GET_PRODUCTS ="GET_PRODUCTS"
 export const ADD_TO_BASKET ="ADD_TO_BASKET"
 export const DELETE_FROM_BASKET ="DELETE_FROM_BASKET"
 export const DELETE_FROM_WISHLIST ="DELETE_FROM_WISHLIST"
 export const DECREASE_QUANTITY ="DECREASE_QUANTITY"
 export const ADD_TO_WISHLIST ="ADD_TO_WISHLIST"
 export const CHANGE_CURRENCY ="CHANGE_CURRENCY"